<nav>
    <div class="nav-left">
        <a href="/" class="nav-logo">LOGO</a>
        <div class="nav-links">
            <a href="#">About</a>
            <a href="#">Contact</a>
        </div>
    </div>
    <?php if (isset($jwtHandler) && $jwtHandler->isLoggedIn()): ?>
        <a href="/logout" class="nav-action">Logout</a>
    <?php else: ?>
        <button class="nav-action">Login</button>
        <div class="nav-login-modal">
            <form action="/login" method="POST">
                <div>
                    <span>
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username">
                    </span>
                    <span>
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password">
                    </span>
                </div>
            
                <input type="submit" value="Login">
            </form>
        </div>
        <script>
            const modal = document.querySelector('.nav-login-modal');
            const modalForm = modal.querySelector('form');
            const loginButton = document.querySelector('.nav-action');

            // Show the modal when the login button is clicked
            loginButton.addEventListener('click', () => {
                modal.style.visibility = 'visible';
                modalForm.classList.add("open");
            });

            // Close the modal when clicking outside of it
            modal.addEventListener('click', (event) => {
                if (event.target === modal) {
                    closeDialogWithAnimation();
                }
            });

            // Function to close the dialog with animation
            function closeDialogWithAnimation() {
                modalForm.classList.remove("open");
                modalForm.classList.add('closing');
                modal.addEventListener('animationend', () => {
                    modalForm.classList.remove('closing');
                    modal.style.visibility = "hidden";
                }, { once: true });
            }
        </script>
    <?php endif; ?>
</nav>
