<nav class="navbar">
    <div class="nav-left">
        <a href="/" class="nav-logo"><img src="public/mango-transparent.png"></a>
        <div class="nav-links">
            <a href="#">About</a>
            <a href="#">Contact</a>
        </div>
    </div>
    <?php if (isset($jwtHandler) && $jwtHandler->isLoggedIn()): ?>
        <!-- <a href="/logout" class="nav-action">Logout</a> -->
        <div class="nav-logged-in-container">
            <div class="nav-logged-in-user">
                <span class="nav-logged-in-username">username</span>
                <span class="nav-logged-in-icon"></span>
            </div>
            <div class="nav-logged-in-items">
                <div class="nav-logged-in-item">
                    <a href="/dashboard">Dashboard</a>
                </div>
                <div class="nav-logged-in-item">
                    <a href="/logout">Logout</a>
                </div>
            </div>
        </div>
    <?php else: ?>
        <button class="nav-action">Login</button>
        <div class="nav-modal nav-login-modal">
            <form action="/login" method="POST">
                <div>
                    <span>
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username">
                    </span>
                    <span>
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password">
                    </span>
                    <span class="remember">
                        <input type="checkbox" name="remember" id="remember">
                        <label for="remember">Remember for 30 days</label>
                    </span>
                </div>
            
                <input type="submit" value="Login">
                <p>Not a user yet? <a href="#">Register</a></p>
            </form>
        </div>
        <div class="nav-modal nav-register-modal">
            <form action="/register" method="POST">
                <div>
                    <span>
                        <label for="username">Username</label>
                        <input type="text" id="username" name="username">
                    </span>
                    <span>
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password">
                    </span>
                    <span>
                        <label for="password">Password</label>
                        <input type="password" id="password" name="password">
                    </span>
                </div>
            
                <input type="submit" value="Register">
                <p>Already a user yet? <a href="#">Login</a></p>
            </form>
        </div>
        <script>
            const loginModal = document.querySelector('.nav-login-modal');
            const registerModal = document.querySelector('.nav-register-modal');
            const loginModalForm = loginModal.querySelector('form');
            const registerModalForm = registerModal.querySelector('form');
            const loginButton = document.querySelector('.nav-action');

            // Show the modal when the login button is clicked
            loginButton.addEventListener('click', () => {
                loginModal.style.visibility = 'visible';
                loginModalForm.classList.add("open");
            });

            // Close the modal when clicking outside of it
            loginModal.addEventListener('click', (event) => {
                if (event.target === modal) {
                    closeDialogWithAnimation();
                }
            });

            // Function to close the dialog with animation
            function closeDialogWithAnimation() {
                loginModalForm.classList.remove("open");
                loginModalForm.classList.add('closing');
                loginModal.addEventListener('animationend', () => {
                    loginModalForm.classList.remove('closing');
                    loginModal.style.visibility = "hidden";
                }, { once: true });
            }
        </script>
    <?php endif; ?>
</nav>
